#!/bin/bash

set -eu -o pipefail

cat > bosh-release/config/private.yml << EOF
---
blobstore:
  options:
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
EOF

cd bosh-release

bosh add-blob ../github-release/*.tar.gz ${BLOB}
bosh upload-blobs

git config --global user.name "CICD Robot"
git config --global user.email "cicd@oakton.digital"

git commit -am 'bump release blob'

cd ..
cp -a bosh-release pushgit

echo "finished uploading a new source blob"
exit 0
