---

groups:
  - name: '((pipeline.name))'
    jobs:
      - create-blob

jobs:
  - name: create-blob
    public: true
    serial: true
    plan:
    - do:
      - aggregate:
        - get: github-release
          trigger: true
          params:
            include_source_tarball: true
        - get: bosh-release
      - task: add-upload-blob
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: concourse/bosh-cli}
          inputs:
            - { name: github-release }
            - { name: bosh-release }
          outputs:
            - { name: pushgit }
          run:
            path: ./bosh-release/ci/scripts/addblob
          params:
            BLOB: ((blob.name))
            AWS_BUCKET: ((aws.bucket))
            AWS_ACCESS_KEY:       ((aws.access_key))
            AWS_SECRET_KEY:       ((aws.secret_key))
      - name: upload-git
        put: bosh-release
        params:
          repository: pushgit/bosh-release

resources:
  - name: github-release
    type: github-release
    source:
      owner: ((git.owner))
      repository: ((git.repo))
      access_token: ((git.access_token))

  - name: bosh-release
    type: git
    source:
      uri:         ((bosh-release.uri))
      branch:      ((bosh-release.branch))
      private_key: ((bosh-release.private_key))

